openapi: "3.0.3"
info:
  title: "Application API"
  description: "Application API"
  version: "1.0.0"
servers:
  - url: "http://0.0.0.0:8080"
paths:
  /api/login:
    post:
      responses:
        "200":
          description: "Успешный вход"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "done"
        "401":
          description: "Несуществующие реквизиты"
  /api/register:
    post:
      responses:
        "201":
          description: "Успешная регистрация"
        "409":
          description: "Пользователь с таким именем уже существует"
  /api/logout:
    post:
      responses:
        "302":
          description: "Успешный выход"
  /api/quotation:
    get:
      responses:
        "200":
          description: "Возвращает JSON c котировками"
        "403":
          description: "Ошибка возвращается при не авторизованном запросе"
components:
  schemas:
